# envlit/dev.yaml - Development environment configuration

extends: ./base.yaml

# Smart flags for dynamic configuration
flags:
  cuda:
    flag: ["--cuda", "-g"]
    default: "0"
    target: "CUDA_VISIBLE_DEVICES"

  backend:
    flag: ["--backend", "-b"]
    default: "c"
    target: "ML_COMPUTE_BACKEND"
    map:
      c: "CPU"
      g: "GPU"
      t: "TPU"

# Environment variables
env:
  # Simple string values (shortcut for 'op: set')
  PROJECT_MODE: "Development"
  DEBUG: "true"
  LOG_LEVEL: "DEBUG"

  # Explicit set operation (equivalent to string value above)
  API_URL:
    op: set
    value: "http://localhost:8000"

  # Explicit unset operation
  PRODUCTION_KEY:
    op: unset

  # Path operations - list of operations (pipeline)
  PATH:
    - op: remove
      value: "/usr/local/old-tools"
    - op: prepend
      value: "./bin"
    - op: prepend
      value: "./scripts"

  # Path operations - single operation (also valid)
  LD_LIBRARY_PATH:
    op: prepend
    value: "./lib"

  # PYTHONPATH - pipeline example
  PYTHONPATH:
    - op: prepend
      value: "./src"
    - op: prepend
      value: "./lib"


# Lifecycle hooks
hooks:
  pre_load:
    - name: "Check dependencies"
      script: |
        echo "🐍 Checking dependencies..."
        if ! command -v python3 &> /dev/null; then
          echo "⚠️  Warning: python3 not found"
        fi

  post_load:
    - name: "Show configuration"
      script: |
        echo "🔧 Development environment loaded"
        echo "   MODE: $PROJECT_MODE"
        echo "   CUDA: $CUDA_VISIBLE_DEVICES"
        echo "   Backend: $ML_COMPUTE_BACKEND"

  pre_unload:
    - name: "Save state"
      script: "echo '💾 Saving development state...'"

  post_unload:
    - name: "Cleanup"
      script: "echo '✨ Development environment unloaded'"
