"""
Shell script generation from configuration.
Generates bash scripts that can be sourced to load/unload environments.
"""

import os
import re
from typing import Any

from envlit.constants import SNAPSHOT_VAR_NAME
from envlit.operations import apply_operations, normalize_env_value, validate_operation

_VALID_VAR_NAME = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")


def generate_load_script(config: dict[str, Any], flag_overrides: dict[str, str] | None = None) -> str:  # noqa: C901
    """
    Generate a shell script to load an environment configuration.

    The generated script follows the sandwich pattern:
    1. envlit-internal-track begin (capture snapshot A)
    2. Pre-load hooks
    3. Environment variable exports
    4. Post-load hooks
    5. envlit-internal-track end (capture snapshot B, update state)
    Args:
        config: Configuration dictionary with env, flags, and hooks sections.
        flag_overrides: Optional dictionary of flag values to override defaults.

    Returns:
        Shell script as a string.
    """
    lines = ["#!/bin/bash", "# Generated by envlit", ""]

    # 1. Begin tracking - capture snapshot and export it
    lines.append("# Capture beginning state")
    lines.append(f"{SNAPSHOT_VAR_NAME}=$(envlit-internal-track begin)")
    lines.append(f"export {SNAPSHOT_VAR_NAME}")
    lines.append("")

    # 2. Pre-load hooks
    if "hooks" in config and "pre_load" in config["hooks"]:
        lines.append("# Pre-load hooks")
        for hook in config["hooks"]["pre_load"]:
            lines.append(f"# Hook: {hook['name']}")
            lines.append(hook["script"])
        lines.append("")

    # 3. Environment variable exports
    lines.append("# Environment variables")
    env_section = dict(config.get("env", {}))

    # Apply flag overrides first
    if flag_overrides:
        for flag_name, flag_value in flag_overrides.items():
            if "flags" in config and flag_name in config["flags"]:
                flag_config = config["flags"][flag_name]
                target_var = flag_config.get("target")
                if target_var:
                    # Check if there's a value mapping
                    if "map" in flag_config and flag_value in flag_config["map"]:
                        mapped_value = flag_config["map"][flag_value]
                        env_section[target_var] = mapped_value
                    else:
                        env_section[target_var] = flag_value

    for var_name, var_value in env_section.items():
        if not _VALID_VAR_NAME.match(var_name):
            raise ValueError(f"Invalid environment variable name '{var_name}': must match [a-zA-Z_][a-zA-Z0-9_]*")
        try:
            # Extract interpolate flag (only meaningful on single-dict ops)
            interpolate = True
            if isinstance(var_value, dict) and "interpolate" in var_value:
                interpolate = bool(var_value["interpolate"])
                var_value = {k: v for k, v in var_value.items() if k != "interpolate"}

            # Normalize value to list of operations
            operations = normalize_env_value(var_value)

            # Validate each operation
            for op in operations:
                validate_operation(op)

            # Get initial value from environment
            initial_value = os.environ.get(var_name)

            # Apply operations to get final value
            final_value = apply_operations(initial_value, operations)

            # Generate shell command based on final value
            if final_value is None:
                lines.append(f"unset {var_name}")
            elif interpolate:
                lines.append(f'export {var_name}="{_escape_interpolated(final_value)}"')
            else:
                lines.append(f"export {var_name}='{_escape_literal(final_value)}'")
        except ValueError as e:
            raise ValueError(f"Error processing variable '{var_name}': {e}") from e
    lines.append("")

    # 4. Post-load hooks
    if "hooks" in config and "post_load" in config["hooks"]:
        lines.append("# Post-load hooks")
        for hook in config["hooks"]["post_load"]:
            lines.append(f"# Hook: {hook['name']}")
            lines.append(hook["script"])
        lines.append("")

    # 5. End tracking - use temp file for Bash 3.2 compatibility (macOS default)
    lines.append("# Capture ending state and update state record")
    lines.append("__ENVLIT_TEMP=$(mktemp)")
    lines.append('envlit-internal-track end > "$__ENVLIT_TEMP"')
    lines.append('source "$__ENVLIT_TEMP"')
    lines.append('rm -f "$__ENVLIT_TEMP"')

    # 6. Clean up temporary snapshot
    lines.append("# Clean up temporary snapshot")
    lines.append(f"unset {SNAPSHOT_VAR_NAME}")

    return "\n".join(lines)


def generate_unload_script(config: dict[str, Any]) -> str:
    """
    Generate a shell script to unload an environment configuration.

    The script will:
    1. Run pre_unload hooks
    2. Call state restoration logic (handled by internal tracker)
    3. Run post_unload hooks

    Args:
        config: Configuration dictionary with hooks section.

    Returns:
        Shell script as a string.
    """
    lines = ["#!/bin/bash", "# Generated by envlit unload", ""]

    # 1. Pre-unload hooks
    if "hooks" in config and "pre_unload" in config["hooks"]:
        lines.append("# Pre-unload hooks")
        for hook in config["hooks"]["pre_unload"]:
            lines.append(f"# Hook: {hook['name']}")
            lines.append(hook["script"])
        lines.append("")

    # 2. Restore original state - use temp file for Bash 3.2 compatibility (macOS default)
    lines.append("# Restore original environment state")
    lines.append("__ENVLIT_TEMP=$(mktemp)")
    lines.append('envlit-internal-track restore > "$__ENVLIT_TEMP"')
    lines.append('source "$__ENVLIT_TEMP"')
    lines.append('rm -f "$__ENVLIT_TEMP"')
    lines.append("")

    # 3. Post-unload hooks
    if "hooks" in config and "post_unload" in config["hooks"]:
        lines.append("# Post-unload hooks")
        for hook in config["hooks"]["post_unload"]:
            lines.append(f"# Hook: {hook['name']}")
            lines.append(hook["script"])
        lines.append("")

    return "\n".join(lines)


def _escape_interpolated(value: str) -> str:
    r"""
    Escape a value for use inside double quotes, preserving ${VAR}/$VAR references.

    Any $-sign that is not part of a valid variable reference is escaped as \$.
    To include a literal $ alongside variable expansion, use interpolate: false
    for the whole value instead.
    """
    # Step 1: Stash all $VAR / ${…} patterns so they survive escaping
    var_refs: dict[str, str] = {}
    var_counter = [0]

    def replace_var(match: re.Match) -> str:
        placeholder = f"__ENVLIT_VAR_{var_counter[0]}__"
        var_refs[placeholder] = match.group(0)
        var_counter[0] += 1
        return placeholder

    # Matches $VAR and ${VAR} with optional modifiers (:-default, :0:5, /old/new, etc.)
    # and the ${#VAR} length operator. Does NOT support nested expansions like
    # ${VAR:-${OTHER}} — the inner } would terminate the match early.
    VAR_PATTERN = re.compile(
        r"\$([a-zA-Z_][a-zA-Z0-9_]*)"  # Simple $var
        r"|\${#?([a-zA-Z_][a-zA-Z0-9_]*)(?::?[^}]*)?}"  # ${var} or ${#var} with modifiers
    )
    temp_value = VAR_PATTERN.sub(replace_var, value)

    # Step 2: Escape characters that are special inside double quotes.
    # Note: real newlines (\x0a) become the two-char sequence \n here, which bash
    # does NOT interpret as a newline inside double quotes. Use interpolate: false
    # (single-quote mode) if the value contains literal newlines.
    temp_value = temp_value.replace("\\", "\\\\")
    temp_value = temp_value.replace("$", "\\$")
    temp_value = temp_value.replace("`", "\\`")
    temp_value = temp_value.replace('"', '\\"')
    temp_value = temp_value.replace("\n", "\\n")

    # Step 3: Restore variable references verbatim
    for placeholder, original in var_refs.items():
        temp_value = temp_value.replace(placeholder, original)

    return temp_value


def _escape_literal(value: str) -> str:
    """
    Escape a value for use inside single quotes (everything is literal).

    The only character that needs handling inside single quotes is the
    single quote itself, via the 'close-escape-reopen' trick.
    """
    return value.replace("'", "'\\''")


def escape_shell_value(value: str, interpolate: bool = True) -> str:
    r"""
    Escape a value for use in a shell script.

    Args:
        value: The value to escape.
        interpolate: When True (default), preserve $VAR / ${VAR} references so
            the shell expands them at runtime (value goes inside double quotes).
            When False, treat the entire value as literal — no shell expansion
            occurs (value goes inside single quotes). Use interpolate=False
            whenever the value contains a literal $ that should not be expanded.

    Returns:
        Escaped value ready to be wrapped in the appropriate quote style.
        The quoting character is chosen automatically by ``generate_load_script``.
    """
    if interpolate:
        return _escape_interpolated(value)
    return _escape_literal(value)
